*** Starting uWSGI 2.0.21 (64bit) on [Sat Jan 28 18:34:50 2023] ***
compiled with version: 9.4.0 on 28 January 2023 08:07:22
os: Linux-5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022
nodename: astlexbudler.cafe24.com
machine: x86_64
clock source: unix
detected number of CPU cores: 6
current working directory: /home/github/apptoaster/apptoaster
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/github/apptoaster/apptoaster/
your processes number limit is 3753
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/github/apptoaster/apptoaster/apptoaster.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/github/apptoaster/venv_linux
Set PythonHome to /home/github/apptoaster/venv_linux
Python main interpreter initialized at 0x5653640b2570
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/home/github/apptoaster/apptoaster/./apptoaster/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9291)
spawned uWSGI worker 1 (pid: 9292, cores: 1)
spawned uWSGI worker 2 (pid: 9293, cores: 1)
spawned uWSGI worker 3 (pid: 9294, cores: 1)
spawned uWSGI worker 4 (pid: 9295, cores: 1)
spawned uWSGI worker 5 (pid: 9296, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 9295|app: -1|req: -1/1] 58.127.225.174 () {42 vars in 752 bytes} [Sat Jan 28 18:35:11 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 9296|app: -1|req: -1/2] 58.127.225.174 () {40 vars in 677 bytes} [Sat Jan 28 18:35:11 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 9296|app: -1|req: -1/3] 58.127.225.174 () {42 vars in 752 bytes} [Sat Jan 28 18:35:15 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 9292|app: -1|req: -1/4] 58.127.225.174 () {40 vars in 677 bytes} [Sat Jan 28 18:35:15 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Sat Jan 28 18:35:54 2023 - uWSGI worker 5 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jan 28 18:35:54 2023 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jan 28 18:35:54 2023 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jan 28 18:35:54 2023 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jan 28 18:35:54 2023 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.21 (64bit) on [Sat Jan 28 18:37:16 2023] ***
compiled with version: 9.4.0 on 28 January 2023 08:07:22
os: Linux-5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022
nodename: astlexbudler.cafe24.com
machine: x86_64
clock source: unix
detected number of CPU cores: 6
current working directory: /home/github/apptoaster/apptoaster
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/github/apptoaster/apptoaster/
your processes number limit is 3753
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/github/apptoaster/apptoaster/apptoaster.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/github/apptoaster/venv_linux
Set PythonHome to /home/github/apptoaster/venv_linux
Python main interpreter initialized at 0x555f020c1500
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/home/github/apptoaster/apptoaster/./apptoaster/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9315)
spawned uWSGI worker 1 (pid: 9316, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 9316|app: -1|req: -1/1] 58.127.225.174 () {42 vars in 752 bytes} [Sat Jan 28 18:38:01 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 9316|app: -1|req: -1/2] 58.127.225.174 () {40 vars in 677 bytes} [Sat Jan 28 18:38:01 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 9316|app: -1|req: -1/3] 58.127.225.174 () {42 vars in 752 bytes} [Sat Jan 28 18:38:01 2023] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 9316|app: -1|req: -1/4] 58.127.225.174 () {40 vars in 677 bytes} [Sat Jan 28 18:38:01 2023] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/github/apptoaster/apptoaster
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/home/github/apptoaster/apptoaster/apptoaster.sock)
running /usr/bin/uwsgi
realpath() of apptoaster_uwsgi.ini failed: No such file or directory [core/utils.c line 3662]
